### ISSUE TITLE
Exception when building docs

### ISSUE THREAD

**Issue by nijel** [michaeljones/breathe#195]
When building [Gammu manual](https://github.com/gammu/gammu/tree/master/docs/manual), I get following error:

```
# Sphinx version: 1.3.1
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:
#   Running Sphinx v1.3.1
#   loading pickled environment...
#   not yet created
#   loading intersphinx inventory from https://docs.python.org/3.4/objects.inv...
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 112 source files that are out of date
#   updating environment:
#   112 added, 0 changed, 0 removed
#   reading sources... [  0%] c/api
#   reading sources... [  1%] c/backup
# Loaded extensions:
#   breathe (unknown version) from /home/nijel/gammu/gammu/docs/manual/breathe/__init__.pyc
#   sphinx.ext.graphviz (1.3.1) from /usr/lib/python2.7/dist-packages/sphinx/ext/graphviz.pyc
#   alabaster (0.7.3) from /usr/lib/python2.7/dist-packages/alabaster/__init__.pyc
#   sphinx.ext.intersphinx (1.3.1) from /usr/lib/python2.7/dist-packages/sphinx/ext/intersphinx.pyc
#   configext (unknown version) from /home/nijel/gammu/gammu/docs/manual/configext.pyc
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 259, in build
    self.doctreedir, self.app))
  File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 618, in update
    self._read_serial(docnames, app)
  File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 638, in _read_serial
    self.read_doc(docname, app)
  File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 791, in read_doc
    pub.publish()
  File "/usr/lib/python2.7/dist-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 126, in read
    self.parse()
  File "/usr/lib/python2.7/dist-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2727, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 328, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 396, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 283, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2302, in explicit_markup
    self.explicit_list(blank_finish)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2332, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 320, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2605, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2312, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2055, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2104, in run_directive
    result = directive_instance.run()
  File "/home/nijel/gammu/gammu/docs/manual/breathe/directives.py", line 501, in run
    mask_factory)
  File "/home/nijel/gammu/gammu/docs/manual/breathe/directive/base.py", line 88, in render
    return object_renderer.render()
  File "/home/nijel/gammu/gammu/docs/manual/breathe/renderer/rst/doxygen/compound.py", line 220, in render
    self.update_signature(signode)
  File "/home/nijel/gammu/gammu/docs/manual/breathe/renderer/rst/doxygen/compound.py", line 379, in update_signature
    signode.children[0][0] = self.node_factory.Text("enum ")
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 582, in __setitem__
    self.children[key] = item
IndexError: list assignment index out of range
```

Using Sphinx 1.3.1 and breathe from git. Same happens with 4.0.0.

To reproduce with Gammu sources you need CMake installed and run make manual-html in the top level directory (this generates doxygen XML and conf.py for Sphinx to find it).

**Comment by nijel** [comment]
The documentation builds without exception when using breathe 3.2.0.

**Comment by michaeljones** [comment]
I've had a quick look but no resolved it yet. The problem seems to be that on line 379 of `compound.py` the `self.children` is not what we expect. If I copy the C code for `GSM_BackupFormat` into the Breathe examples and run it then the `self.children` is:
```
[<desc_annotation: <#text: 'type '>>, <desc_name: <#text: 'GSM_BackupFormat'>>]
```
But running it in the Gammu code base I get:
```
[<desc_type: >, <desc_name: <#text: 'GSM_BackupFormat'>>]
```
Which then fails that line.

I'm not quite sure why this is happening. Perhaps because in the Gammu code base there are some cross references which I'm not copying across to my test. So something that is resolving to text in my test is resolving to a link to another element in the full set up. Not sure though. More investigation needed but I don't have the time right now. Soon I hope.

Michael

**Comment by michaeljones** [comment]
@vitaut, you might need to provide your knowledge on this one. I suspect it is actually because the file is being classified as `C` rather than `C++` and I'm not sure that we, or maybe Sphinx, supports enums in `C`. Can you remember the details? The comment in the section of code below, where we configure the Sphinx directives that we delegate to, seems to indicate there are some issues here (from directives.py line 806):

```
        'typedef': (cpp.CPPTypeObject, 'type'),
        'union': (cpp.CPPTypeObject, 'type'),
        'namespace': (cpp.CPPTypeObject, 'type'),
        # Use CPPClassObject for enum values as the cpp domain doesn't have a directive for
        # enum values and CPPMemberObject requires a type.
        'enumvalue': (cpp.CPPClassObject, 'member'),
        'define': (c.CObject, 'macro')
    }
```

**Comment by vitaut** [comment]
Thanks for looking into it @michaeljones, I was a bit busy lately to debug this myself. You are right, the problem is with differences in enum handling in C and C++ domains. It should be fixed in #196 which also explains a bit what's going on.

**Comment by michaeljones** [comment]
Thanks for that mate. Happy to be able to find the time to help a little but very glad you could weigh in.

**Comment by michaeljones** [comment]
The fix has been merged. @nijel are you able to check with the latest on `master`? Happy to do a new release if it works for you.

**Comment by nijel** [comment]
Thanks, it now does not fail with exception, however I still have problem described in #194.

**Comment by nijel** [comment]
Any plans for release? Having new version with fixes for this and #194 would really help me.

**Comment by michaeljones** [comment]
Hey! Thanks for the prompting. I will try to do one tonight (I'm in the UK.)

**Comment by michaeljones** [comment]
Done! Hope it works for you. https://pypi.python.org/pypi/breathe/4.1.0

**Comment by nijel** [comment]
Thanks!
