### ISSUE TITLE
Duplicate declaration warning for overloaded functions

### ISSUE THREAD

**Issue by jfolz** [michaeljones/breathe#504]
All of my overloaded functions cause multiple duplicate declaration warnings per `doxygenfunction`. Everything seems to be present in the generated docs. Links and index are generated correctly as far as I can tell. But I have 42 warnings currently, 41 of which are "duplicate declaration" and I'm trying to figure out where the issue lies. Doxygen seems to be fine, that leaves breathe or sphinx.

tensor.h excerpt:
```
namespace py = pybind11;
namespace augpy {

/**
Returns `true` if the tensor is contiguous.
*/
bool check_contiguous(DLTensor* tensor);

/**
Returns `true` if the tensor is contiguous.
*/
bool check_contiguous(CudaTensor* tensor);

/**
Returns `true` if the array is contiguous.
*/
bool check_contiguous(py::buffer_info &array);

// namespace augpy
}
```

Doxygen xml:
```
<codeline lineno="466"><highlight class="keywordtype">bool</highlight><highlight class="normal"><sp/><ref refid="namespaceaugpy_1a68e8a04b48012c53494525a7a5de985a" kindref="member">check_contiguous</ref>(<ref refid="structDLTensor" kindref="compound">DLTensor</ref>*<sp/>tensor);</highlight></codeline>
<codeline lineno="467"><highlight class="normal"></highlight></codeline>
<codeline lineno="468"><highlight class="normal"></highlight></codeline>
<codeline lineno="472"><highlight class="keywordtype">bool</highlight><highlight class="normal"><sp/><ref refid="namespaceaugpy_1a68e8a04b48012c53494525a7a5de985a" kindref="member">check_contiguous</ref>(CudaTensor*<sp/>tensor);</highlight></codeline>
<codeline lineno="473"><highlight class="normal"></highlight></codeline>
<codeline lineno="474"><highlight class="normal"></highlight></codeline>
<codeline lineno="478"><highlight class="keywordtype">bool</highlight><highlight class="normal"><sp/><ref refid="namespaceaugpy_1a68e8a04b48012c53494525a7a5de985a" kindref="member">check_contiguous</ref>(py::buffer_info<sp/>&amp;array);</highlight></codeline>
```

tensor.rst excerpt:
```
L.129    .. doxygenfunction:: augpy::check_contiguous(CudaTensor *)
L.130    .. doxygenfunction:: augpy::check_contiguous(DLTensor *)
L.131    .. doxygenfunction:: augpy::check_contiguous(py::buffer_info&)
```

And the warnings:
```
tensor.rst:129: WARNING: Duplicate declaration, bool augpy::check_contiguous(CudaTensor  * tensor)
tensor.rst:130: WARNING: Duplicate declaration, bool augpy::check_contiguous(DLTensor  *)
tensor.rst:130: WARNING: Duplicate declaration, bool augpy::check_contiguous(DLTensor  * tensor)
tensor.rst:131: WARNING: Duplicate declaration, bool augpy::check_contiguous(DLTensor  *)
tensor.rst:131: WARNING: Duplicate declaration, bool augpy::check_contiguous(CudaTensor  *)
tensor.rst:131: WARNING: Duplicate declaration, bool augpy::check_contiguous(py::buffer_info & array)
```

Note that the line numbers in the rst and the warnings are inconsistent. Every inclusion of a function variant seem to produce one more warning than the last one and includes all the previous variants. Sometimes with and sometimes without parameter names.

I also tried the exact whitespace config that is given in the warnings, but that confuses the build process even more, as it can no longer determine which of the variants it is. Same if I include the namespace in the parameter type.

Python 3.6
Sphinx==2.4.4
breathe==4.14.1
doxygen==1.8.14

**Comment by vermeeren** [comment]
Just to make sure: there is only one `.. doxygenfunction:: augpy::check_contiguous(CudaTensor *)` in all of the RST docs? It might be that only the function name is used to identify it internally somehow, which would explain issues with overloaded functions.

There have been quite some major changes with Sphinx 3, so there is a (tiny) chance this might have been fixed. If possible could you try with latest released Sphinx and Breathe versions?

**Comment by jfolz** [comment]
Yep, there's only those 3 mentions in the entire doc.
I later saw that Sphinx 3 was released, so I updated to Sphinx==3.0.1 and breathe==4.15.0.
After fixing deprecations and such the warnings are still there.

**Comment by vermeeren** [comment]
Sphinx docs very much indicate this is fully supported in the C++ domain, see http://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#overloaded-member-functions. Though the `Duplicate declaration` warning is emitted in Sphinx at https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/domains/cpp.py#L6556.

I suspect either Breathe doesn't pass the function arguments to Sphinx properly in some way or Sphinx's C++ domain uses only the main name (and namespace) to store the symbol somehow? @jakobandersen could you share thoughts?

**Comment by vermeeren** [comment]
Released fix in v4.18.1, should be resolved now.

@jfolz Could you test with the new release?

**Comment by jfolz** [comment]
@vermeeren 4.18.1 fixes all warnings as described above. I got `Unable to resolve multiple matches for function` for all of them, which I could resolve by specifying each `doxygenfunction` precisely as it was given in the list of alternatives, including parameter names.

Two duplicate declaration warnings were not fixed though:
```
WARNING: Duplicate declaration, std::tuple< size_t, size_t, size_t > augpy::meminfo (int device_id)
```
Since the project is public now, [here's a link to the code](https://gitlab.com/jfolz/augpy/-/blob/ef39b18651d13a17985fdb004c332c378c44d99f/augpy/function.h#L29).

The second one I noticed since the build log has cleaned up a lot now (oops):
```
WARNING: Duplicate declaration, DLManagedTensor
```
`DLManagedTensor` is a struct which is included by a `doxygenfile` directive and also the base class of my `augpy::CudaTensor`, which is included in the docs via `doxygenclass`.

Dunno if this is related or a separate issue, but this did not happen with 4.15.0:
```
WARNING: Error when parsing function declaration.
If the function has no return type:
  Error in declarator or parameters-and-qualifiers
  Invalid C++ declaration: Parameterised "noexcept" not yet implemented. [error at 24]
    ~CudaTensor () noexcept(false)
    ------------------------^
If the function has a return type:
  Error in declarator
  If declarator-id with parameters-and-qualifiers:
    Invalid C++ declaration: Expected identifier in nested name. [error at 12]
      ~CudaTensor () noexcept(false)
      ------------^
  If parenthesis in noptr-declarator:
    Error in declarator or parameters-and-qualifiers
    If pointer to member declarator:
      Invalid C++ declaration: Expected identifier in nested name. [error at 13]
        ~CudaTensor () noexcept(false)
        -------------^
    If declarator-id:
      Invalid C++ declaration: Expected identifier in nested name. [error at 13]
        ~CudaTensor () noexcept(false)
        -------------^
```

**Comment by vermeeren** [comment]
Thanks for the reply, will reopen this for now as the edge cases aren't fully covered yet it seems. Good to hear most instances of the problem are resolved now though.

**Comment by jakobandersen** [comment]
(The last part regarding ``noexcept`` should be fixed when using the 3.x branch of Sphinx (future v3.1), sphinx-doc/sphinx#7485)

**Comment by jfolz** [comment]
@jakobandersen Thanks, I updated to sphinx 3.0.3 :)

For reference, [here's the `doxygenclass`](https://gitlab.com/jfolz/augpy/-/blob/9e3ef0256c914d11db65a8fa1a4a5faac1805366/doc/source/cpp/tensor.rst#L41) and [here's the `doxygenfile`](https://gitlab.com/jfolz/augpy/-/blob/9e3ef0256c914d11db65a8fa1a4a5faac1805366/doc/source/cpp/tensor.rst#L164).

**Comment by vermeeren** [comment]
@jfolz The `Unable to resolve multiple matches for function` should be a lot better with #606, released in Breathe 4.25.0.

However the `Duplicate declaration` warning likely still exists as before, as there haven't be real changes there afaik.

**Comment by jakobandersen** [comment]
@jfolz, I couldn't immediately build the docs, and I'm unsure which issues are left here. Can you provide an update?
