### ISSUE TITLE
Example build outputs bug message

### ISSUE THREAD

**Issue by t-b** [michaeljones/breathe#688]
When I execute `make html` with 9fb353a8 (changelog: update for #687, 2021-05-02) and sphinx 3.5.4 I get

```
E:\projekte\breathe\documentation\source\specific.rst.rst:131: WARNING: Parsing of expression failed. Using fallback parser. Error was:
Error in postfix expression, expected primary expression or type.
If primary expression:
  Invalid C++ declaration: Expected identifier in nested name, got keyword: static [error at 28]
    int bar (int n, int a[static n])
    ----------------------------^
If type:
  Invalid C++ declaration: Expected identifier in nested name, got keyword: static [error at 28]
    int bar (int n, int a[static n])
    ----------------------------^

E:\projekte\breathe\documentation\source\specific.rst:131: WARNING: Parsing of expression failed. Using fallback parser. Error was:
Error in postfix expression, expected primary expression or type.
If primary expression:
  Invalid C++ declaration: Expected identifier in nested name, got keyword: static [error at 28]
    int bar (int n, int a[static n])
    ----------------------------^
If type:
  Invalid C++ declaration: Expected identifier in nested name, got keyword: static [error at 28]
    int bar (int n, int a[static n])
    ----------------------------^

E:\projekte\breathe\documentation\source\specific.rst.rst:131: WARNING: Index id generation for C++ object "int bar(int n, int a[static n])" failed, please report as bug (id=_CPPv4NUt17_ex_specific_image3barEiAstatic n_i).
E:\projekte\breathe\documentation\source\specific.rst:167: WARNING: Duplicate C declaration, also defined at doxygen:27.
Declaration is '.. c:macro:: MAX(A, B)'.
E:\projekte\breathe\documentation\source\specific.rst:3: WARNING: Duplicate ID: "cpp_inherited_membersclass_base_1a08c79e0729b179e5f5ae0a6c28f7a9a7".
```

**Comment by vermeeren** [comment]
@t-b With Debian bullseye provided packages and only Breathe set via `PYTHONPATH` it's building fine here, this is with Sphinx 3.4.3, perhaps something changed on the Sphinx side?

@jakobandersen Anything you know of?

**Comment by jakobandersen** [comment]
No, I can't recall anything that should cause this. I think it is an old problem where an example is not explicitly labelled as C code, so the C++ directive rightly complains. Should be fixed with #690.

**Comment by t-b** [comment]
Thanks both.

With #690 I still get

```
E:\projekte\breathe\documentation\source\specific.rst:62: WARNING: Duplicate C declaration, also defined at domains:81.
Declaration is '.. c:function:: void frob_foos (void *Frobs)'.
E:\projekte\breathe\documentation\source\specific.rst.rst:131: WARNING: Parsing of expression failed. Using fallback parser. Error was:
Error in postfix expression, expected primary expression or type.
If primary expression:
  Invalid C++ declaration: Expected identifier in nested name, got keyword: static [error at 28]
    int bar (int n, int a[static n])
    ----------------------------^
If type:
  Invalid C++ declaration: Expected identifier in nested name, got keyword: static [error at 28]
    int bar (int n, int a[static n])
    ----------------------------^
```

but this now less warning output.

**Comment by vermeeren** [comment]
Same as @t-b above, get a single warning instead of two currently.

**Comment by jakobandersen** [comment]
Indeed, not sure why it did't get rid of both.

**Comment by vermeeren** [comment]
Merged the at least partial fix, though a single one still remains.
